### ISSUE TITLE
Create a new page where we display a random NFT in full screen.

### ISSUE THREAD

**Issue by tarasbob** [PredictionExplorer/randomwalknft-front-end#47]
Let's create a page called `random NFT` If you go to that page a random NFT will be chosen and displayed full screen (like on the front page). Add a link to the bottom of the page to the detail page of that NFT. The link text should be the NFT number. Like "#2357".

I think they look really nice when displayed on the entire page. It will let people get a feel for the NFTs.

**Comment by ionel2988** [comment]
done

**Comment by ionel2988** [comment]
fixed
